config/routes.rb
Rails.application.routes.draw do
  get 'videos/autocomplete'
  get 'users/autocomplete'
  root "static_pages#top"
  resources :categories, param: :name, only: [:show]
  resources :shared_videos do
    resources :comments, only: [:create, :destroy]
  end
  resource :profile, only: [:show, :edit, :update] do
    get 'diagnosis', on: :collection, as: 'diagnosis'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  namespace :public do
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        get 'confirmation'
        post 'back'
        get 'back', to: 'contacts#back'
        get 'done'
      end
    end

    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'users/autocomplete', to: 'users#autocomplete', as: :autocomplete_user
  get 'videos/autocomplete', to: 'videos#autocomplete', as: :autocomplete_video
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shared_video
  belongs_to :video

  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_video
  before_action :set_comment, only: [:destroy]

  def create
    @shared_video = SharedVideo.find(params[:shared_video_id])
    @comment = @shared_video.comments.build(comment_params.merge(user: current_user))
    if @comment.save
      redirect_to shared_video_path(@shared_video)
    else
      respond_to do |format|
        format.html { render 'shared_videos/show' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("errors", partial: "shared/error_messages", locals: { object: @comment })
        end
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @shared_video = @comment.shared_video
    @comment.destroy
    redirect_to shared_video_path(@shared_video), notice: 'コメントが削除されました。'
  end

  def update
    @comment.reload unless @comment.update(comment_update_params)
  end

  private

  def set_video
    shared_video = SharedVideo.find(params[:shared_video_id])
    @video = shared_video.video
  end

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :video_id)
  end
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag(comment.user.profile&.avatar_url || "Golf_sample_2.jpg", class: "rounded-circle", width: 50, height: 50) %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.name %> </h3>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <% if current_user.own?(comment) && comment.persisted? %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to shared_video_comment_path(@shared_video, comment), class: 'delete-comment-link', data: {turbo_method: :delete, turbo_confirm: "削除しますか？" } do %>
            <i class="bi bi-trash-fill icon-large"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form-<%= @comment.id %>">
  <div class="col-md-12">
    <div id="errors">
      <%= render 'shared/error_messages', object: @comment %>
    </div>
    <%= form_with model: [ @shared_video, @comment ], local: true, class: "d-flex align-items-end" do |f| %>
      <%= f.hidden_field :video_id, value: @shared_video.video_id %>
      <div class="form-group flex-grow-1 me-2">
        <%= f.label :body, 'コメント', class: "form-label" %>
        <%= f.text_area :body, class: "form-control shadow-sm", placeholder: 'コメントを入力してください...', rows: 3 %>
      </div>
      <div>
        <button type="submit" class="btn btn-primary px-3 py-2">
          <i class="bi bi-send"></i>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form-<%= @comment.id %>" do %>
    <%= render 'comments/form', comment: @comment, board: @comment.board %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, board: @comment.board %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove id = "comment-form-<%= @comment.id %>" %>