config/routes.rb
Rails.application.routes.draw do
  get 'videos/autocomplete'
  get 'users/autocomplete'
  root "static_pages#top"
  resources :categories, param: :name, only: [:show]
  resources :shared_videos do
    resources :comments, only: [:create, :destroy]
  end
  resource :profile, only: [:show, :edit, :update] do
    get 'diagnosis', on: :collection, as: 'diagnosis'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  namespace :public do
    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm'
        get 'confirmation'
        post 'back'
        get 'back', to: 'contacts#back'
        get 'done'
      end
    end

    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'users/autocomplete', to: 'users#autocomplete', as: :autocomplete_user
  get 'videos/autocomplete', to: 'videos#autocomplete', as: :autocomplete_video
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class = 'header-top'>
    <h1>GolfUp</h1>
  </div>
  <nav class='navbar navbar-expand-lg navigation'>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <i class="bi bi-list"></i>
    </button>
    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown '>
          <%= link_to t('header.basic'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.address') , category_path('address'), class: 'dropdown-item' %>
            <%= link_to t('header.grip') , category_path('grip'), class: 'dropdown-item' %>
            <%= link_to t('header.basic_swing') , category_path('basic_swing'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.club'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.driver') , category_path('driver'), class: 'dropdown-item' %>
            <%= link_to t('header.iron') , category_path('iron'), class: 'dropdown-item' %>
            <%= link_to t('header.wood') , category_path('wood'), class: 'dropdown-item' %>
            <%= link_to t('header.utility') , category_path('utility'), class: 'dropdown-item' %>
            <%= link_to t('header.putter') , category_path('putter'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.environment'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.bunker') , category_path('bunker'), class: 'dropdown-item' %>
            <%= link_to t('header.rough') , category_path('rough'), class: 'dropdown-item' %>
            <%= link_to t('header.gradient') , category_path('gradient'), class: 'dropdown-item' %>
            <%= link_to t('header.strong_wind') , category_path('strong_wind'), class: 'dropdown-item' %>
            <%= link_to t('header.rain') , category_path('rain'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.green_around'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.approach') , category_path('approach'), class: 'dropdown-item' %>
            <%= link_to t('header.lob_shot') , category_path('lob_shot'), class: 'dropdown-item' %>
            <%= link_to t('header.ground_ball') , category_path('ground_ball'), class: 'dropdown-item' %>
          </div>
        </li>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.shot_miss'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.hook') , category_path('hook'), class: 'dropdown-item' %>
            <%= link_to t('header.slice') , category_path('slice'), class: 'dropdown-item' %>
            <%= link_to t('header.duff') , category_path('duff'), class: 'dropdown-item' %>
            <%= link_to t('header.topped_shot') , category_path('topped_shot'), class: 'dropdown-item' %>
            <%= link_to t('header.shank') , category_path('shank'), class: 'dropdown-item' %>
            <%= link_to t('header.chunk') , category_path('chunk'), class: 'dropdown-item' %>
            <%= link_to t('header.skied_ball') , category_path('skied_ball'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.mastering_items'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.flight_distance') , category_path('flight_distance'), class: 'dropdown-item' %>
            <%= link_to t('header.stability') , category_path('stability'), class: 'dropdown-item' %>
            <%= link_to t('header.management') , category_path('management'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.target'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.hundred_or_less') , category_path('hundred_or_less'), class: 'dropdown-item' %>
            <%= link_to t('header.ninety_or_less') , category_path('ninety_or_less'), class: 'dropdown-item' %>
            <%= link_to t('header.eighty_or_less') , category_path('eighty_or_less'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item'>
          <%= link_to t('header.diagnosis'), diagnosis_profile_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to t('header.recommended'), shared_videos_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'ログイン' , new_user_session_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to '新規登録' , new_user_registration_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= t("errors.messages.not_saved", count: object.errors.count) %></h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='navbar-footer'>
    <div class='nav-item'>
      <%= link_to t('footer.privacy') , privacy_path, class: 'nav-link' %>
    </div>
    <div class='nav-item'>
      <%= link_to t('footer.terms_of_service') , terms_path, class: 'nav-link' %>
    </div>
    <div class='nav-item'>
      <%= link_to t('footer.contact') , public_contacts_new_path, class: 'nav-link' %>
    </div>
  </div>
  <div class='footer-copyright'>
    <p>© 2024 GolfUp. Copyright All Rights Reserved.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class = 'header-top'>
    <h1>GolfUp</h1>
  </div>
  <nav class='navbar navbar-expand-lg navigation'>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <i class="bi bi-list"></i>
    </button>
    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown '>
          <%= link_to t('header.basic'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.address') , category_path('address'), class: 'dropdown-item' %>
            <%= link_to t('header.grip') , category_path('grip'), class: 'dropdown-item' %>
            <%= link_to t('header.basic_swing') , category_path('basic_swing'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.club'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.driver') , category_path('driver'), class: 'dropdown-item' %>
            <%= link_to t('header.iron') , category_path('iron'), class: 'dropdown-item' %>
            <%= link_to t('header.wood') , category_path('wood'), class: 'dropdown-item' %>
            <%= link_to t('header.utility') , category_path('utility'), class: 'dropdown-item' %>
            <%= link_to t('header.putter') , category_path('putter'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.environment'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.bunker') , category_path('bunker'), class: 'dropdown-item' %>
            <%= link_to t('header.rough') , category_path('rough'), class: 'dropdown-item' %>
            <%= link_to t('header.gradient') , category_path('gradient'), class: 'dropdown-item' %>
            <%= link_to t('header.strong_wind') , category_path('strong_wind'), class: 'dropdown-item' %>
            <%= link_to t('header.rain') , category_path('rain'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.green_around'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.approach') , category_path('approach'), class: 'dropdown-item' %>
            <%= link_to t('header.lob_shot') , category_path('lob_shot'), class: 'dropdown-item' %>
            <%= link_to t('header.ground_ball') , category_path('ground_ball'), class: 'dropdown-item' %>
          </div>
        </li>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.shot_miss'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.hook') , category_path('hook'), class: 'dropdown-item' %>
            <%= link_to t('header.slice') , category_path('slice'), class: 'dropdown-item' %>
            <%= link_to t('header.duff') , category_path('duff'), class: 'dropdown-item' %>
            <%= link_to t('header.topped_shot') , category_path('topped_shot'), class: 'dropdown-item' %>
            <%= link_to t('header.shank') , category_path('shank'), class: 'dropdown-item' %>
            <%= link_to t('header.chunk') , category_path('chunk'), class: 'dropdown-item' %>
            <%= link_to t('header.skied_ball') , category_path('skied_ball'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.mastering_items'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.flight_distance') , category_path('flight_distance'), class: 'dropdown-item' %>
            <%= link_to t('header.stability') , category_path('stability'), class: 'dropdown-item' %>
            <%= link_to t('header.management') , category_path('management'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to t('header.target'), '#', class: 'nav-link', 'data-bs-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' %>
          <div class='dropdown-menu'>
            <%= link_to t('header.hundred_or_less') , category_path('hundred_or_less'), class: 'dropdown-item' %>
            <%= link_to t('header.ninety_or_less') , category_path('ninety_or_less'), class: 'dropdown-item' %>
            <%= link_to t('header.eighty_or_less') , category_path('eighty_or_less'), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to t('header.diagnosis'), diagnosis_profile_path, class: 'nav-link' %>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to t('header.recommended'), shared_videos_path, class: 'nav-link' %>
        </li>
        <li class='nav-item dropdown '>
          <%= link_to('#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true',  expanded: 'false' }, id: 'header-profile' ) do %>
            <i class="bi bi-house-door-fill"></i>
          <% end %>
          <div class='dropdown-menu'>
            <div class='dropdown-item'><%= current_user.name %></div>
            <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <% if @profile.present? %>
              <%= image_tag @profile.avatar.url, class: 'rounded-circle mr15', width: '40', height: '40' %>
            <% else %>
              <%= image_tag 'Golf_sample.jpg', class: 'rounded-circle mr15', width: '40', height: '40' %>
            <% end %>
          <% end %>
            <div class='dropdown-divider'></div>
            <%= link_to t('header.profile'), profile_path, class: 'dropdown-item' %>
            <%= link_to t('header.logout'), destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>